name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        if: "!contains(github.event.head_commit.message, '#skip')"
        run: echo "Hello World"

      - name: Discord notification - Success
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          description: "🎉 Successfully deployed new version"
          details: "Commit: ${{ github.sha }}"

      - name: Discord notification - Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          description: "❌ Build failed!"
          details: |
            Commit: ${{ github.sha }}

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

  list:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls -la
