name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        if: "!contains(github.event.head_commit.message, '#skip')"
        run: echo "Hello World"

      - name: Discord notification - Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "🎉 Deployment Successful"
          description: "Successfully deployed new version\nCommit: ${{ github.sha }}"
          color: 0x2ecc71

      - name: Discord notification - Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ Build Failed"
          description: |
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
          color: 0xe74c3c

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

  list:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls -la
