name: Hello World

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  hello:
    if: "!contains(github.event.head_commit.message, '#skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

  list:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls -la
