name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        if: "!contains(github.event.head_commit.message, '#skip')"
        run: echo "Hello World"

      - name: Discord notification - Success
        if: "!contains(github.event.head_commit.message, 'discord') && success()"
        uses: rjstone/discord-webhook-notify@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🎉 Successfully deployed new version from commit: ${{ github.sha }}"

      - name: Discord notification - Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ❌ Build failed!
            Commit: ${{ github.sha }}

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

  list:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls -la
